name: open_media_station_base
description: "The base package for the Open Media Station Flutter applications."
version: 0.1.1
homepage: https://openmediastation.org

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_http: ^2.0.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  oauth2_client: ^3.3.0
  qr_flutter: ^4.1.0
  random_string: ^2.3.1
  device_info_plus: ^11.3.0
  cached_network_image: ^3.4.1
  icons_plus: ^5.0.0
  alphabet_scrollbar: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
