name: open_media_station_base
description: "The base package for the Open Media Station Flutter applications."
version: 0.0.1
homepage: https://openmediastation.org

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0